services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    depends_on:
      - db

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root #reemplazar por variable de entorno de .env no olvidarrrrrrrrrrrrrrrr
      MYSQL_DATABASE: flask_db #reemplazar por variable de entorno de .env
      MYSQL_ROOT_HOST: '%' #allow host access
    command: --default-authentication-plugin=mysql_native_password #native authentication
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data: