services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - FLASK_APP=run.py
      - DATABASE_URL=mysql://root:${MYSQL_ROOT_PASSWORD}@db/${MYSQL_DATABASE}
      - PAGERDUTY_API_KEY=${PAGERDUTY_API_KEY}
    depends_on:
      - db
    command: ["flask", "run", "--host=0.0.0.0"]
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE} 
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST} #allow host access
    command: --default-authentication-plugin=mysql_native_password #native authentication
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data: {} 