services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root #reemplazar por variable de entorno de .env no olvidarrrrrrrrrrrrrrrr
      MYSQL_DATABASE: flask_db #reemplazar por variable de entorno de .env
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: